### ISSUE TITLE
In-app browser detection

### ISSUE THREAD

**Issue by mikehwagz** [TimvanScherpenzeel/detect-ua#2]
Hi Tim 👋

Thanks for open-sourcing this utility! Have been searching for a robust, yet tiny browser/device sniffer, and this really gets the job done.

Would you be open to adding detection for mobile webviews for specific social media apps? If so, I'd be happy to make a PR!

I've been using the following functions to detect facebook, instagram, pinterest, and twitter webviews:
```js
function checkFb() {
  return ua.indexOf('fban') > -1 || ua.indexOf('fbav') > -1
}

function checkIg() {
  return ua.indexOf('instagram') > -1
}

function checkTwitter() {
  return ua.indexOf('twitter') > -1
}

function checkPinterest() {
  return ua.indexOf('pinterest') > -1
}
```

**Comment by TimvanScherpenzeel** [comment]
Hi @mikehwagz, thanks for your kind comment. Unfortunately I think in the light of keeping this library under 1kb there is not enough space to provide this functionality for you in this library.
