### ISSUE TITLE
problem with SSR

### ISSUE THREAD

**Issue by gtolarc** [TimvanScherpenzeel/detect-ua#4]
In the latest version of drei, an error related to SSR occurs in the part that uses this library.

Can you use this flag(const isServer = typeof window === 'undefined';) to skip the next 2 parts? @TimvanScherpenzeel 

https://github.com/TimvanScherpenzeel/detect-ua/blob/master/src/index.ts#L25
https://github.com/TimvanScherpenzeel/detect-ua/blob/master/src/index.ts#L36

**Comment by TimvanScherpenzeel** [comment]
Resolved in detect-gpu 1.5.0
